### PR TITLE
MPLv2

### PR DESCRIPTION
**Pull request by chorrell**
- Relicense gomanta as MPLv2, fixes https://github.com/joyent/gomanta/issues/5
- Updates Copyright to the current year (2016)

### CODE REVIEW

**Comment by lloydde** [comment]
As MPL is a "per file" license the license header should be in each file.

"To apply the Mozilla Public License to software that you have written, add the header from Exhibit A of the license to each source code file in your project."
https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by misterbisson** [comment]
Thank you!

🏡 🚶

**Comment by tgross** [comment]
It would be really nice if this library had a makefile that set up the workspace properly... it's unclear to me how the `github.com/joyent/gocommon/testing` package works with this library given just the contents of this repo.

In any event, @chorrell I tried to run the tests and got a bunch of errors that look related to the setup of the test suite fixtures, but this one looks like it's a legit compilation error:

> src/github.com/joyent/gomanta/localservices/manta/service_http_test.go:65: cannot use s.HTTPSuite.Mux (type *httprouter.Router) as type *"net/http".ServeMux in argument to s.service.SetupHTTP

**Comment by tgross** [comment]
> this one looks like it's a legit compilation error

@chorrell it looks like I'm getting that against `master` as well. I think this is safe to merge and then maybe we can circle back to figure out what the test suite story is supposed to be.

**Comment by chorrell** [comment]
Cool, thanks for the sanity check @tgross. I'll go ahead an merge and will open a "fix tests" issue.

**Pull request merged**
